/** @type {import('tailwindcss').Config} */
export default {
  darkMode: "class",
  content: ["./index.html", "./src/**/*.{js,jsx}"],
  theme: {
    extend: {
      colors: {
        background: "#051424",
        "surface-tint": "#00daf3",
        "primary-container": "#00e5ff",
        error: "#ffb4ab",
        "surface-container-highest": "#273647",
        "secondary-container": "#4a4949",
        "on-surface": "#d4e4fa",
        "on-tertiary-fixed": "#1a1a2a",
        "error-container": "#93000a",
        "on-primary-container": "#00626e",
        "on-secondary-container": "#bab8b7",
        "on-secondary-fixed-variant": "#474646",
        "surface-dim": "#051424",
        "inverse-on-surface": "#233143",
        tertiary: "#edeaff",
        "on-secondary": "#313030",
        "on-primary": "#00363d",
        primary: "#c3f5ff",
        "on-background": "#d4e4fa",
        "surface-bright": "#2c3a4c",
        "on-tertiary-container": "#58576a",
        "surface-container-low": "#0d1c2d",
        "tertiary-fixed": "#e3e0f7",
        "primary-fixed": "#9cf0ff",
        "on-error": "#690005",
        "secondary-fixed-dim": "#c8c6c5",
        "on-tertiary-fixed-variant": "#464557",
        "on-surface-variant": "#bac9cc",
        "tertiary-fixed-dim": "#c6c4da",
        "outline-variant": "#3b494c",
        secondary: "#c8c6c5",
        "on-error-container": "#ffdad6",
        "inverse-surface": "#d4e4fa",
        "tertiary-container": "#d0cee4",
        "on-secondary-fixed": "#1c1b1b",
        "on-tertiary": "#2f2f40",
        "surface-variant": "#273647",
        "surface-container-lowest": "#010f1f",
        outline: "#849396",
        surface: "#051424",
        "primary-fixed-dim": "#00daf3",
        "on-primary-fixed-variant": "#004f58",
        "secondary-fixed": "#e5e2e1",
        "surface-container-high": "#1c2b3c",
        "inverse-primary": "#006875",
        "surface-container": "#122131",
        "on-primary-fixed": "#001f24",
      },
      borderRadius: {
        DEFAULT: "0.125rem",
        lg: "0.25rem",
        xl: "0.5rem",
        full: "0.75rem",
      },
      spacing: {
        "container-max": "1440px",
        gutter: "20px",
        xs: "4px",
        base: "4px",
        sm: "8px",
        md: "16px",
        lg: "24px",
        xl: "40px",
      },
      fontFamily: {
        "body-md": ["Geist", "sans-serif"],
        "body-lg": ["Geist", "sans-serif"],
        "label-md": ["JetBrains Mono", "monospace"],
        "headline-lg-mobile": ["Geist", "sans-serif"],
        "headline-xl": ["Geist", "sans-serif"],
        "headline-md": ["Geist", "sans-serif"],
        "headline-lg": ["Geist", "sans-serif"],
        "label-sm": ["JetBrains Mono", "monospace"],
      },
      fontSize: {
        "body-md": ["14px", { lineHeight: "20px", fontWeight: "400" }],
        "body-lg": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "label-md": ["12px", { lineHeight: "16px", letterSpacing: "0.05em", fontWeight: "500" }],
        "headline-lg-mobile": ["24px", { lineHeight: "32px", fontWeight: "600" }],
        "headline-xl": ["40px", { lineHeight: "48px", letterSpacing: "-0.02em", fontWeight: "700" }],
        "headline-md": ["20px", { lineHeight: "28px", fontWeight: "600" }],
        "headline-lg": ["32px", { lineHeight: "40px", letterSpacing: "-0.01em", fontWeight: "600" }],
        "label-sm": ["10px", { lineHeight: "14px", letterSpacing: "0.08em", fontWeight: "500" }],
      },
    },
  },
  plugins: [],
};
