# Application
spring.application.name=mini-nms
server.port=8080

# MongoDB
spring.mongodb.host=localhost
spring.mongodb.port=27017
spring.mongodb.database=nms_db

# Logging
logging.level.com.nms=INFO
logging.level.org.springframework.data.mongodb=WARN
logging.pattern.console=%d{HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n

# Scheduler
spring.task.scheduling.pool.size=5

#kafka
spring.kafka.bootstrap-servers=${SPRING_KAFKA_BOOTSTRAP_SERVERS:localhost:9092}

